targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/models/**.dart
      flutter_sheet_localization_generator|flutter_sheet_localization:
        generate_for:
          - lib/others/localization.dart
      json_serializable:
        options:
          explicit_to_json: true