name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.3

  google_fonts: ^2.1.0

  firebase_core: ^1.6.0
  firebase_messaging: ^10.0.7
  firebase_crashlytics: ^2.2.1

  logger: ^1.1.0
  url_launcher: ^6.0.9
  intl: ^0.17.0
  device_info: ^2.0.2
  package_info: ^2.0.2
  path_provider: ^2.0.5
  app_settings: ^4.1.1
  mdi: ^5.0.0-nullsafety.0
  timeago: 3.0.2
  octo_image: ^1.0.0+1
  flutter_image: ^4.1.0
  cached_network_image: ^3.1.0
  flutter_riverpod: ^1.0.0-dev.7
  flutter_app_badger: ^1.3.0
  flutter_sheet_localization: ^5.1.1
  freezed_annotation: ^0.14.3
  sqflite: ^2.0.0+4
  dio: ^4.0.0


dev_dependencies:
  flutter_sheet_localization_generator: ^5.1.7
  build_runner: ^2.1.2
  freezed: ^0.14.5
  json_serializable: ^5.0.2
  flutter_lints: ^1.0.4

dependency_overrides:
  analyzer: ^2.3.0
  meta: ^1.7.0
