name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:

  cupertino_icons: ^1.0.5

  google_fonts: ^4.0.5

  firebase_core: ^2.15.0 #firebaseCore

  firebase_messaging: ^14.6.5 #firebaseMessaging

  firebase_crashlytics: ^3.3.4 #firebaseCrashlytics
  
  firebase_auth: ^4.7.2 #firebaseAuth

  app_settings: 4.2.0 #appSettings

  google_maps_flutter: ^2.4.0 #googleMaps

  google_maps_cluster_manager: ^3.0.0+1 #googleMaps

  image_cropper: ^4.0.1 #imagePicker

  image_picker: ^0.8.9 #imagePicker

  flutter_image_compress: ^2.0.4 #imagePicker

  photo_view: ^0.14.0 #photoView

  smooth_page_indicator: ^1.1.0 #photoView

  map_launcher: ^2.5.0+1 #mapLauncherff

  flutter_svg: ^2.0.7 #flutterSvg

  app_links: ^3.4.3 #appLinks

  share_plus: ^7.0.2 #sharePlus

  pinput: ^2.3.0 #pinCodeFields

  hive: ^2.2.3 #hive

  hive_flutter: ^1.1.0 #hive

  sqflite: ^2.3.0 #sqflite

  flutter_app_badger: ^1.5.0 #flutterAppBadger

  location: ^4.4.0 #location

  logger: ^1.4.0

  url_launcher: ^6.1.12

  intl: ^0.18.0

  device_info_plus: ^9.0.2

  package_info_plus: ^4.0.2

  path_provider: ^2.0.15

  mdi: ^5.0.0-nullsafety.0

  timeago: 3.0.2

  octo_image: ^1.0.2

  flutter_image: ^4.1.6

  cached_network_image: ^3.2.3

  flutter_riverpod: ^2.3.6

  freezed_annotation: ^2.4.1

  json_annotation: ^4.8.1

  dio: ^4.0.6 #dio
  
  get_it: ^7.6.0


  flutter_sheet_localization: #^5.1.1
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization
  
  
  flutter:
    sdk: flutter

  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.6

  freezed: ^2.4.1

  json_serializable: ^6.7.1

  flutter_lints: ^2.0.2


  flutter_test:
    sdk: flutter


#override dependeinces
dependency_overrides:
  http: ^1.0.0



  flutter_sheet_localization_generator: #^5.1.7
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization_generator

flutter:
  assets:
    - flags/
    - google_fonts/