name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:

  cupertino_icons: ^1.0.6

  google_fonts: ^6.1.0

  firebase_core: ^2.24.2 #firebaseCore

  firebase_messaging: ^14.7.10 #firebaseMessaging

  firebase_crashlytics: ^3.4.9 #firebaseCrashlytics
  
  firebase_auth: ^4.16.0 #firebaseAuth

  app_settings: 4.2.0 #appSettings

  google_maps_flutter: ^2.5.3 #googleMaps

  google_maps_cluster_manager: ^3.1.0 #googleMaps

  image_cropper: ^5.0.1 #imagePicker

  image_picker: ^1.0.7 #imagePicker

  flutter_image_compress: ^2.1.0 #imagePicker

  photo_view: ^0.14.0 #photoView

  smooth_page_indicator: ^1.1.0 #photoView

  map_launcher: ^3.1.0 #mapLauncherff

  flutter_svg: ^2.0.9 #flutterSvg

  app_links: ^3.5.0 #appLinks

  share_plus: ^7.2.1 #sharePlus

  pinput: ^3.0.1 #pinCodeFields

  hive: ^2.2.3 #hive

  hive_flutter: ^1.1.0 #hive

  sqflite: ^2.3.0 #sqflite

  flutter_app_badger: ^1.5.0 #flutterAppBadger

  location: ^5.0.3 #location

  logger: ^2.0.2+1

  url_launcher: ^6.2.3

  intl: ^0.18.1

  device_info_plus: ^9.1.1

  package_info_plus: ^5.0.1

  path_provider: ^2.1.2

  mdi: ^5.0.0-nullsafety.0

  timeago: 3.0.2

  octo_image: ^2.0.0

  flutter_blurhash: ^0.8.2
  
  flutter_image: ^4.1.10

  cached_network_image: ^3.3.1

  flutter_riverpod: ^2.4.9

  freezed_annotation: ^2.4.1

  json_annotation: ^4.8.1

  dio: ^4.0.6 #dio
  
  get_it: ^7.6.7


  flutter_sheet_localization: #^5.1.1
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization
  
  
  flutter:
    sdk: flutter

  
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.8

  freezed: ^2.4.6

  json_serializable: ^6.7.1

  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

  flutter_sheet_localization_generator: #^5.1.7
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization_generator

#override dependeinces
dependency_overrides:
  http: ^1.1.0

flutter:
  assets:
    - flags/
    - google_fonts/