name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4

  google_fonts: ^2.3.1

  firebase_core: ^1.13.1 #firebaseCore
  firebase_messaging: ^11.2.11 #firebaseMessaging
  firebase_crashlytics: ^2.5.3 #firebaseCrashlytics

  app_settings: ^4.1.1 #appSettings

  google_maps_flutter: ^2.1.3 #googleMaps
  google_maps_cluster_manager: ^3.0.0+1 #googleMaps

  image_cropper: ^1.5.0 #imagePicker
  image_picker: ^0.8.4+11 #imagePicker
  flutter_image_compress: ^1.1.0 #imagePicker

  photo_view: ^0.13.0 #photoView
  smooth_page_indicator: ^1.0.0+2 #photoView

  map_launcher: ^2.2.1+1 #mapLauncher

  flutter_svg: ^1.0.3 #flutterSvg

  app_links: ^3.0.1 #appLinks

  share_plus: ^4.0.3 #sharePlus

  pin_code_fields: ^7.3.0 #pinCodeFields

  hive: ^2.1.0 #hive
  hive_flutter: ^1.1.0 #hive
  sqflite: ^2.0.2 #sqflite


  logger: ^1.1.0
  url_launcher: ^6.0.20
  intl: ^0.17.0

  device_info_plus: ^3.2.2

  package_info_plus: ^1.4.0

  path_provider: ^2.0.9
  mdi: ^5.0.0-nullsafety.0
  timeago: 3.0.2

  octo_image: ^1.0.1
  flutter_image: ^4.1.0
  cached_network_image: ^3.2.0

  flutter_riverpod: ^1.0.3
  flutter_app_badger: ^1.3.0 #flutterAppBadger
  flutter_sheet_localization: ^5.1.1
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  dio: ^4.0.4

  get_it: ^7.2.0



dev_dependencies:
  flutter_sheet_localization_generator: ^5.1.7
  build_runner: ^2.1.8
  freezed: ^1.1.1
  json_serializable: ^6.1.5
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  analyzer: ^3.2.0
  meta: ^1.7.0

flutter:
  assets:
    - flags/
    - google_fonts/
