name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4

  google_fonts: ^2.3.2

  firebase_core: ^1.17.0 #firebaseCore
  firebase_messaging: ^11.4.0 #firebaseMessaging
  firebase_crashlytics: ^2.8.0 #firebaseCrashlytics

  app_settings: ^4.1.6 #appSettings

  google_maps_flutter: ^2.1.5 #googleMaps
  google_maps_cluster_manager: ^3.0.0+1 #googleMaps

  image_cropper: ^2.0.2 #imagePicker
  image_picker: ^0.8.5+3 #imagePicker
  flutter_image_compress: ^1.1.0 #imagePicker

  photo_view: ^0.14.0 #photoView
  smooth_page_indicator: ^1.0.0+2 #photoView

  map_launcher: ^2.2.2 #mapLauncher

  flutter_svg: ^1.0.3 #flutterSvg

  app_links: ^3.2.0 #appLinks

  share_plus: ^4.0.4 #sharePlus

  pin_code_fields: ^7.4.0 #pinCodeFields

  hive: ^2.1.0 #hive
  hive_flutter: ^1.1.0 #hive
  sqflite: ^2.0.2+1 #sqflite


  logger: ^1.1.0
  url_launcher: ^6.1.2
  intl: ^0.17.0

  device_info_plus: ^3.2.3

  package_info_plus: ^1.4.2

  path_provider: ^2.0.10
  mdi: ^5.0.0-nullsafety.0
  timeago: 3.0.2

  octo_image: ^1.0.2
  flutter_image: ^4.1.0
  cached_network_image: ^3.2.1

  flutter_riverpod: ^1.0.4
  flutter_app_badger: ^1.4.0 #flutterAppBadger

  flutter_sheet_localization: #^5.1.1
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization

  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  dio: ^4.0.6

  get_it: ^7.2.0



dev_dependencies:

  flutter_sheet_localization_generator: #^5.1.7
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization_generator

  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - flags/
    - google_fonts/
