name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:

  cupertino_icons: ^1.0.6

  google_fonts: ^6.2.1

  firebase_core: ^2.29.0 #firebaseCore

  firebase_messaging: ^14.8.1 #firebaseMessaging

  firebase_crashlytics: ^3.5.1 #firebaseCrashlytics
  
  firebase_auth: ^4.19.1 #firebaseAuth

  app_settings: 4.2.0 #appSettings

  google_maps_flutter: ^2.6.0 #googleMaps

  google_maps_cluster_manager: ^3.1.0 #googleMaps

  image_cropper: ^5.0.1 #imagePicker

  image_picker: ^1.0.7 #imagePicker

  flutter_image_compress: ^2.2.0 #imagePicker

  photo_view: ^0.14.0 #photoView

  smooth_page_indicator: ^1.1.0 #photoView

  map_launcher: ^3.3.0 #mapLauncherff

  flutter_svg: ^2.0.10+1 #flutterSvg

  app_links: ^4.0.1 #appLinks

  share_plus: ^8.0.3 #sharePlus

  pinput: ^4.0.0 #pinCodeFields

  hive: ^2.2.3 #hive

  hive_flutter: ^1.1.0 #hive

  sqflite: ^2.3.3 #sqflite

  flutter_app_badger: ^1.5.0 #flutterAppBadger

  location: ^6.0.1 #location

  logger: ^2.2.0

  url_launcher: ^6.2.5

  intl: ^0.18.1

  device_info_plus: ^10.1.0

  package_info_plus: ^7.0.0

  path_provider: ^2.1.2

  mdi: ^5.0.0-nullsafety.0

  timeago: 3.0.2

  octo_image: ^2.0.0

  flutter_blurhash: ^0.8.2
  
  flutter_image: ^4.1.11

  cached_network_image: ^3.3.1

  flutter_riverpod: ^2.5.1

  freezed_annotation: ^2.4.1

  json_annotation: ^4.8.1

  dio: ^4.0.6 #dio
  
  get_it: ^7.6.8


  flutter_sheet_localization: #^5.1.1
      git:
        url: https://github.com/SalehHub/flutter_sheet_localization.git
        path: flutter_sheet_localization
  
  
  flutter:
    sdk: flutter

  
  flutter_localizations:
    sdk: flutter

  http: any
  # flutter_test: any
dev_dependencies:
  build_runner: ^2.4.9

  freezed: ^2.5.1

  json_serializable: ^6.7.1

  flutter_lints: ^3.0.2
  flutter_sheet_localization_generator: #^5.1.7
      git:
        url: https://github.com/SalehHub/flutter_sheet_localization.git
        path: flutter_sheet_localization_generator

#override dependeinces
dependency_overrides:
  http: ^1.1.0

flutter:
  assets:
    - flags/
    - google_fonts/