name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5

  google_fonts: ^3.0.1

  firebase_core: ^1.20.0 #firebaseCore

  firebase_messaging: ^12.0.1 #firebaseMessaging

  firebase_crashlytics: ^2.8.6 #firebaseCrashlytics
  firebase_auth: ^3.5.0 #firebaseAuth

  app_settings: ^4.1.8 #appSettings

  google_maps_flutter: ^2.1.9 #googleMaps

  google_maps_cluster_manager: ^3.0.0+1 #googleMaps

  image_cropper: ^2.0.3 #imagePicker

  image_picker: ^0.8.5+3 #imagePicker

  flutter_image_compress: ^1.1.0 #imagePicker

  photo_view: ^0.14.0 #photoView

  smooth_page_indicator: ^1.0.0+2 #photoView

  map_launcher: ^2.2.3 #mapLauncher

  flutter_svg: ^1.1.1+1 #flutterSvg

  app_links: ^3.2.0 #appLinks

  share_plus: ^4.0.10 #sharePlus

  pin_code_fields: ^7.4.0 #pinCodeFields

  hive: ^2.2.3 #hive

  hive_flutter: ^1.1.0 #hive

  sqflite: ^2.0.3 #sqflite

  logger: ^1.1.0

  url_launcher: ^6.1.5

  intl: ^0.17.0

  device_info_plus: ^4.0.1

  package_info_plus: ^1.4.3

  path_provider: ^2.0.11

  mdi: ^5.0.0-nullsafety.0

  timeago: 3.0.2

  octo_image: ^1.0.2

  flutter_image: ^4.1.3

  cached_network_image: ^3.2.1

  flutter_riverpod: ^1.0.4

  flutter_app_badger: ^1.4.0 #flutterAppBadger

  freezed_annotation: ^2.1.0

  json_annotation: ^4.6.0

  dio: ^4.0.6
  
  get_it: ^7.2.0

  flutter_sheet_localization: #^5.1.1
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization


dev_dependencies:
  build_runner: ^2.2.0

  freezed: ^2.1.0+1

  json_serializable: ^6.3.1

  flutter_lints: ^2.0.1

  flutter_test:
    sdk: flutter

  flutter_sheet_localization_generator: #^5.1.7
      git:
        url: https://github.com/salehahmedZ/flutter_sheet_localization.git
        path: flutter_sheet_localization_generator

flutter:
  assets:
    - flags/
    - google_fonts/
