name: my_services
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4

  google_fonts: ^2.1.0

  firebase_core: ^1.10.0
  firebase_messaging: ^11.1.0
  firebase_crashlytics: ^2.3.0

  logger: ^1.1.0
  url_launcher: ^6.0.13
  intl: ^0.17.0

  device_info: ^2.0.3
  package_info: ^2.0.2

  path_provider: ^2.0.7
  app_settings: ^4.1.1
  mdi: ^5.0.0-nullsafety.0
  timeago: 3.0.2

  octo_image: ^1.0.0+1
  flutter_image: ^4.1.0
  cached_network_image: ^3.1.0+1

  flutter_riverpod: ^1.0.0
  flutter_app_badger: ^1.3.0
  flutter_sheet_localization: ^5.1.1
  freezed_annotation: ^1.0.0
  json_annotation: ^4.3.0
  sqflite: ^2.0.0+4
  dio: ^4.0.3

  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  flutter_image_compress: ^1.1.0

  photo_view: ^0.13.0


dev_dependencies:
  flutter_sheet_localization_generator: ^5.1.7
  build_runner: ^2.1.5
  freezed: ^1.0.0
  json_serializable: ^6.0.1
  flutter_lints: ^1.0.4

dependency_overrides:
  analyzer: ^2.7.0
  meta: ^1.7.0
